# Generated by Django 3.2.17 on 2023-02-13 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='Pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formularios.pregunta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.TextField(max_length=200),
        ),
    ]
