# Generated by Django 3.2.17 on 2023-02-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formularios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='last_updated',
            new_name='last_update',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='created',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='respuesta',
        ),
    ]
