# Generated by Django 3.2.17 on 2023-02-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formularios', '0002_auto_20230212_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='Pregunta',
            new_name='pregunta',
        ),
    ]
