# Generated by Django 3.2.17 on 2023-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formularios', '0002_auto_20230214_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='respuesta',
            field=models.TextField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
