# Generated by Django 3.2.17 on 2023-02-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seguimientos', '0001_initial'),
        ('Formularios', '0001_initial'),
        ('Departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.TextField(max_length=200)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanInversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('formulario_inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formularios.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlanEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.TextField(max_length=200)),
                ('filtro', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_plan',
            },
        ),
        migrations.CreateModel(
            name='PlanProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan_proceso', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('planes_de_inversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.planinversion')),
                ('seguimiento_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstrategico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_estrategico', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('planes_inversion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.planinversion')),
                ('seguimiento_plan_estrategico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDesarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_desarrollo', models.TextField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('formulario_plan_desarrollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formularios.formulario')),
                ('planes_estrategicos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.planestrategico')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.oficina')),
                ('planes_desarrollo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.plandesarrollo')),
            ],
        ),
    ]
