# Generated by Django 3.2.17 on 2023-02-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seguimientos', '0001_initial'),
        ('Planes', '0001_initial'),
        ('Departamentos', '0001_initial'),
        ('Formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planproceso',
            name='seguimiento_proceso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.seguimiento'),
        ),
        migrations.AddField(
            model_name='planinversion',
            name='formulario_inversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formularios.formulario'),
        ),
        migrations.AddField(
            model_name='planestrategico',
            name='planes_inversion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.planinversion'),
        ),
        migrations.AddField(
            model_name='planestrategico',
            name='seguimiento_plan_estrategico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.seguimiento'),
        ),
        migrations.AddField(
            model_name='plandesarrollo',
            name='formulario_plan_desarrollo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formularios.formulario'),
        ),
        migrations.AddField(
            model_name='plandesarrollo',
            name='planes_estrategicos',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.planestrategico'),
        ),
        migrations.AddField(
            model_name='plan',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.oficina'),
        ),
        migrations.AddField(
            model_name='plan',
            name='planes_desarrollo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.plandesarrollo'),
        ),
    ]
