# Generated by Django 3.2.17 on 2023-02-25 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoplanespecifico',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='tipoplan',
            table='tipo_plan',
        ),
    ]
