# Generated by Django 3.2.17 on 2023-02-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0002_auto_20230219_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplanespecifico',
            name='tipo_general',
            field=models.TextField(max_length=300),
        ),
    ]
