# Generated by Django 3.2.17 on 2023-02-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0002_auto_20230224_2249'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoplanespecifico',
            table=None,
        ),
    ]
