# Generated by Django 3.2.17 on 2023-02-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0003_alter_tipoplanespecifico_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoplanespecifico',
            table='tipo_plan',
        ),
    ]
