# Generated by Django 3.2.17 on 2023-02-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0003_alter_tipoplanespecifico_tipo_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplanespecifico',
            name='tipo_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planes.tipoplan'),
        ),
    ]
