# Generated by Django 3.2.17 on 2023-02-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0004_alter_tipoplanespecifico_tipo_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoplanespecifico',
            name='tipo_general',
        ),
    ]
