# Generated by Django 3.2.17 on 2023-02-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimientos', '0001_initial'),
        ('Planes', '0005_remove_tipoplanespecifico_tipo_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planproceso',
            name='planes_de_inversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.planinversion'),
        ),
        migrations.AlterField(
            model_name='planproceso',
            name='seguimiento_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.seguimiento'),
        ),
    ]
