# Generated by Django 3.2.17 on 2023-02-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimientos', '0001_initial'),
        ('Planes', '0006_auto_20230219_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planproceso',
            name='seguimiento_proceso',
        ),
        migrations.AddField(
            model_name='planproceso',
            name='seguimiento_proceso',
            field=models.ManyToManyField(blank=True, null=True, to='Seguimientos.Seguimiento'),
        ),
    ]
