# Generated by Django 3.2.17 on 2023-02-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimientos', '0001_initial'),
        ('Planes', '0007_auto_20230220_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planproceso',
            name='planes_de_inversion',
        ),
        migrations.AddField(
            model_name='planproceso',
            name='planes_de_inversion',
            field=models.ManyToManyField(blank=True, null=True, to='Planes.PlanInversion'),
        ),
        migrations.RemoveField(
            model_name='planproceso',
            name='seguimiento_proceso',
        ),
        migrations.AddField(
            model_name='planproceso',
            name='seguimiento_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.seguimiento'),
        ),
    ]
