# Generated by Django 3.2.17 on 2023-02-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0008_auto_20230220_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planproceso',
            name='planes_de_inversion',
        ),
        migrations.AddField(
            model_name='planproceso',
            name='planes_de_inversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.planinversion'),
        ),
        migrations.RemoveField(
            model_name='tipoplan',
            name='planes_especificos',
        ),
        migrations.AddField(
            model_name='tipoplan',
            name='planes_especificos',
            field=models.ManyToManyField(to='Planes.TipoPlanEspecifico'),
        ),
    ]
