# Generated by Django 3.2.17 on 2023-02-22 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0009_auto_20230220_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplan',
            name='plan_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Planes.planproceso'),
        ),
    ]
