# Generated by Django 3.2.18 on 2023-03-14 15:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(db_column='id_permiso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ip_crea', models.CharField(max_length=15)),
                ('ip_modifica', models.CharField(max_length=15)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('usuario_crea', models.CharField(max_length=16)),
                ('usuario_modifica', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('ip_crea', models.CharField(max_length=15)),
                ('ip_modifica', models.CharField(max_length=15)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('usuario_crea', models.CharField(max_length=16)),
                ('usuario_modifica', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'ROL',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('usuario', models.CharField(max_length=16, unique=True)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('dependencia', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('ip_crea', models.CharField(max_length=15)),
                ('ip_modifica', models.CharField(max_length=15)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('usuario_crea', models.CharField(max_length=16)),
                ('usuario_modifica', models.CharField(max_length=16)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_crea', models.CharField(max_length=15)),
                ('ip_modifica', models.CharField(max_length=15)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('usuario_crea', models.CharField(max_length=16)),
                ('usuario_modifica', models.CharField(max_length=16)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.rol')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios_Roles',
            },
        ),
        migrations.CreateModel(
            name='Rol_Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_crea', models.CharField(max_length=15)),
                ('ip_modifica', models.CharField(max_length=15)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('usuario_crea', models.CharField(max_length=16)),
                ('usuario_modifica', models.CharField(max_length=16)),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.PROTECT, to='Usuarios.permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='Usuarios.rol')),
            ],
            options={
                'db_table': 'Rol_Permiso',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
