# Generated by Django 3.2.17 on 2023-02-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Formularios', '0001_initial'),
        ('Departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seguimiento_name', models.TextField(max_length=100)),
                ('Formulario_Seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formularios.formulario')),
                ('Formulario_Seguimiento_Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.oficina')),
                ('seguimiento_formulario_pivot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seguimientos.formulario_seguimiento')),
            ],
        ),
    ]
