# Generated by Django 3.2.18 on 2023-03-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamentos', '0001_initial'),
        ('Formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.oficina')),
                ('seguimiento_formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Formularios.formulario')),
            ],
        ),
    ]
