# Generated by Django 3.2.17 on 2023-02-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario_seguimiento',
            old_name='seguimiento_name',
            new_name='formulario_seguimiento',
        ),
    ]
