# Generated by Django 3.2.17 on 2023-02-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0001_initial'),
        ('Seguimientos', '0002_rename_seguimiento_name_formulario_seguimiento_formulario_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_seguimiento',
            name='Formulario_Seguimiento_Plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planes.plan'),
        ),
    ]
