# Generated by Django 3.2.17 on 2023-02-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='oficina',
        ),
    ]
